export const mockStudents = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice@example.com",
    rollNo: "CS2021001",
    department: "Computer Science",
    year: "3rd Year",
    phone: "+1234567890",
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob@example.com",
    rollNo: "CS2021002",
    department: "Computer Science",
    year: "3rd Year",
    phone: "+1234567891",
  },
  {
    id: "3",
    name: "Carol White",
    email: "carol@example.com",
    rollNo: "EE2021001",
    department: "Electrical Engineering",
    year: "2nd Year",
    phone: "+1234567892",
  },
  {
    id: "4",
    name: "David Brown",
    email: "david@example.com",
    rollNo: "ME2021001",
    department: "Mechanical Engineering",
    year: "4th Year",
    phone: "+1234567893",
  },
  {
    id: "5",
    name: "Emma Davis",
    email: "emma@example.com",
    rollNo: "CS2022001",
    department: "Computer Science",
    year: "2nd Year",
    phone: "+1234567894",
  },
]

export const mockCourses = [
  {
    id: "1",
    code: "CS301",
    name: "Data Structures",
    credits: 4,
    faculty: "Dr. Sarah Miller",
    department: "Computer Science",
    semester: "Fall 2024",
  },
  {
    id: "2",
    code: "CS302",
    name: "Algorithms",
    credits: 4,
    faculty: "Dr. John Davis",
    department: "Computer Science",
    semester: "Fall 2024",
  },
  {
    id: "3",
    code: "EE201",
    name: "Circuit Theory",
    credits: 3,
    faculty: "Dr. Michael Chen",
    department: "Electrical Engineering",
    semester: "Fall 2024",
  },
  {
    id: "4",
    code: "ME401",
    name: "Thermodynamics",
    credits: 4,
    faculty: "Dr. Lisa Anderson",
    department: "Mechanical Engineering",
    semester: "Fall 2024",
  },
  {
    id: "5",
    code: "CS401",
    name: "Machine Learning",
    credits: 4,
    faculty: "Dr. Robert Taylor",
    department: "Computer Science",
    semester: "Fall 2024",
  },
]

export const mockFaculty = [
  {
    id: "1",
    name: "Dr. Sarah Miller",
    email: "sarah.miller@college.edu",
    department: "Computer Science",
    designation: "Professor",
    phone: "+1234567800",
    specialization: "Data Structures",
  },
  {
    id: "2",
    name: "Dr. John Davis",
    email: "john.davis@college.edu",
    department: "Computer Science",
    designation: "Associate Professor",
    phone: "+1234567801",
    specialization: "Algorithms",
  },
  {
    id: "3",
    name: "Dr. Michael Chen",
    email: "michael.chen@college.edu",
    department: "Electrical Engineering",
    designation: "Professor",
    phone: "+1234567802",
    specialization: "Circuit Design",
  },
  {
    id: "4",
    name: "Dr. Lisa Anderson",
    email: "lisa.anderson@college.edu",
    department: "Mechanical Engineering",
    designation: "Assistant Professor",
    phone: "+1234567803",
    specialization: "Thermodynamics",
  },
  {
    id: "5",
    name: "Dr. Robert Taylor",
    email: "robert.taylor@college.edu",
    department: "Computer Science",
    designation: "Professor",
    phone: "+1234567804",
    specialization: "Machine Learning",
  },
]

export const mockAttendance = [
  {
    id: "1",
    studentId: "1",
    studentName: "Alice Johnson",
    rollNo: "CS2021001",
    courseCode: "CS301",
    courseName: "Data Structures",
    date: "2024-01-15",
    status: "present",
  },
  {
    id: "2",
    studentId: "2",
    studentName: "Bob Smith",
    rollNo: "CS2021002",
    courseCode: "CS301",
    courseName: "Data Structures",
    date: "2024-01-15",
    status: "present",
  },
  {
    id: "3",
    studentId: "3",
    studentName: "Carol White",
    rollNo: "EE2021001",
    courseCode: "EE201",
    courseName: "Circuit Theory",
    date: "2024-01-15",
    status: "absent",
  },
  {
    id: "4",
    studentId: "4",
    studentName: "David Brown",
    rollNo: "ME2021001",
    courseCode: "ME401",
    courseName: "Thermodynamics",
    date: "2024-01-15",
    status: "present",
  },
  {
    id: "5",
    studentId: "5",
    studentName: "Emma Davis",
    rollNo: "CS2022001",
    courseCode: "CS302",
    courseName: "Algorithms",
    date: "2024-01-15",
    status: "present",
  },
]

export const mockMarks = [
  {
    id: "1",
    studentId: "1",
    studentName: "Alice Johnson",
    rollNo: "CS2021001",
    courseCode: "CS301",
    courseName: "Data Structures",
    marks: 85,
    maxMarks: 100,
    grade: "A",
  },
  {
    id: "2",
    studentId: "2",
    studentName: "Bob Smith",
    rollNo: "CS2021002",
    courseCode: "CS301",
    courseName: "Data Structures",
    marks: 78,
    maxMarks: 100,
    grade: "B+",
  },
  {
    id: "3",
    studentId: "3",
    studentName: "Carol White",
    rollNo: "EE2021001",
    courseCode: "EE201",
    courseName: "Circuit Theory",
    marks: 92,
    maxMarks: 100,
    grade: "A+",
  },
  {
    id: "4",
    studentId: "4",
    studentName: "David Brown",
    rollNo: "ME2021001",
    courseCode: "ME401",
    courseName: "Thermodynamics",
    marks: 88,
    maxMarks: 100,
    grade: "A",
  },
  {
    id: "5",
    studentId: "5",
    studentName: "Emma Davis",
    rollNo: "CS2022001",
    courseCode: "CS302",
    courseName: "Algorithms",
    marks: 95,
    maxMarks: 100,
    grade: "A+",
  },
]
